sudo: required

services:
    - docker


before_install:
    - docker build -t lakshyajit165/notes-client ./notes-client
    - docker build -t lakshyajit165/notes ./notes

script:
    - echo "skipping tests"

after_success:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push lakshyajit165/notesapp