version: '3'
services:
  notes-client:
    build:
      context: ./notes-client/notesapp
      dockerfile: Dockerfile
    depends_on: 
      - notes-service
    restart: always
    container_name: notes-client
    network_mode: host
    hostname: localhost

  notes-service:
    build:
      context: ./notes
      dockerfile: Dockerfile
    depends_on:
      - mysql
    restart: always
    container_name: notes-service
    network_mode: host
    hostname: localhost


  mysql:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=notes
    container_name: notesdb
    network_mode: host
    hostname: localhost